debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.fastcampus.fastcampusprojectboardreview: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: winter
    #    username: karina
    password: Imtestpassword!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true


---

spring:
  config:
    activate:
      on-profile: testdb
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    driver-class-name: org.h2.Driver
    username: sa
  sql:
    init:
      mode: always
  test.database.replace: none #document? ?????? ?????? ???

---

spring:
  config.activate.on-profile: heroku
  datasource:
    url: ${JAWSDB_URL}
  jpa.hibernate.ddl-auto: create
  sql.init.mode: always